# Generated by Django 5.1.5 on 2025-01-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='authorId',
            new_name='author',
        ),
    ]
