# Generated by Django 5.1.5 on 2025-03-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='documents'),
        ),
    ]
