# Generated by Django 5.1.5 on 2025-01-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_document_image_document_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(default=3, max_length=20),
            preserve_default=False,
        ),
    ]
