# Generated by Django 4.2.20 on 2025-03-30 19:20

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_document_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(upload_to=users.models.path_and_rename),
        ),
    ]
