# Generated by Django 5.1.5 on 2025-02-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_document_image_document_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
