# Generated by Django 5.1.5 on 2025-02-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_name'),
        ('users', '0002_alter_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='skills',
            field=models.ManyToManyField(related_name='users', to='users.skill'),
        ),
    ]
