# Generated by Django 4.2.20 on 2025-03-30 20:46

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='avatars/default.jpg', upload_to=authentication.models.path_and_rename),
        ),
    ]
