# Generated by Django 5.1.5 on 2025-02-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_company_alter_customuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='rating',
        ),
        migrations.AddField(
            model_name='customuser',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rating_sum',
            field=models.IntegerField(default=0),
        ),
    ]
