# Generated by Django 5.1.5 on 2025-03-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_customuser_image'),
        ('users', '0005_alter_request_respondedusers_alter_review_reviewee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.skill'),
        ),
    ]
